name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t my-app .

    - name: Run Container
      run: docker run -d -p 5000:5000 my-app

    - name: wait for App
      run: sleep 5

    - name: Test Application
      run: curl localhost:5000
